# Generated by Django 3.2.5 on 2021-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerinfo',
            old_name='social_media',
            new_name='social_media_handle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='social_type',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TWITTER', 'Twitter')], default='INSTAGRAM', max_length=10),
        ),
    ]
