# Generated by Django 3.2.5 on 2021-07-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
