# Generated by Django 3.2.5 on 2021-07-06 02:50

from django.db import migrations
import escrowapi.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapi', '0002_auto_20210706_0325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', escrowapi.user_manager.UserManager()),
            ],
        ),
    ]
