# Generated by Django 3.2.5 on 2021-07-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapi', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Customer_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendor_status',
        ),
        migrations.AddField(
            model_name='user',
            name='ACCOUNT_TYPE',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('VENDOR', 'VENDOR')], default='CUSTOMER', max_length=20),
        ),
    ]
