# Generated by Django 3.2.5 on 2021-07-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrowapi', '0006_alter_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('VENDOR', 'VENDOR')], max_length=20),
        ),
    ]
